openapi: "3.0.0"
info:
    title: "An Example Simple OAS Specification"
    version: "1.0.0"
    description: |
        #Sequence diagram for the API - dependencies
        ```mermaid
            sequenceDiagram
            autonumber
                Buyer->>+Shopify Store: Checkout Process
                Shopify Store->>+AL Now App: Present Shoping Option "chekout-options"
                AL Now App->>AL Now Server: Get me some timeslots
                AL Now Server->>HL Back End: Get timeslots for the day
                HL Back End-->> AL Now Server: Return timeslots
                AL Now Server-->>AL Now App: Pass timeslots array ( to do the flow of error...)  
                AL Now App-->>+AL Now App: Save in metafields
                AL Now App-->>AL Now Server: Get a price for {{timeslotID}}
                AL Now Server->>HL Back End: Get me a price for {{timeslotID}}
                HL Back End-->>AL Now Server: Return the price
                AL Now Server-->>AL Now App: Store ( do nothing for now)
                Buyer->>Shopify Store: Complete Order and Payment
                Shopify Store->>Shopify Webhook: Trigger on Success 'orders/create' event
                Shopify Webhook-->>AL Now App: Send the webhook
                AL Now App->>AL Now Server: On 200 OK and IF( Shipping Option == `AddLee Now`)
                AL Now Server->>+HL Back End: Create (POST) /bookings/create the AL Now ( account 50)
                HL Back End-->>-AL Now Server: Return Booking details 
                AL Now Server-->>AL Now App: Pass the booking details 
                AL Now App -->>-AL Now App: Use the AL Now Booking details in Thanks You Extension
                AL Now App-->>Shopify Store: Render the Extention
                Shopify Store->>-Buyer: Render the Thank you page 
        ```
        ### Features

        - Support Standard Markdown / CommonMark and GFM(GitHub Flavored Markdown);
        - Full-featured: Real-time Preview, Image (cross-domain) upload, Preformatted text/Code blocks/Tables insert, Code fold, Search replace, Read only, Themes, Multi-languages, L18n, HTML entities, Code syntax highlighting...;
        - Markdown Extras : Support ToC (Table of Contents), Emoji, Task lists, @Links...;
        - Compatible with all major browsers (IE8+), compatible Zepto.js and iPad;
        - Support identification, interpretation, fliter of the HTML tags;
        - Support TeX (LaTeX expressions, Based on KaTeX), Flowchart and Sequence Diagram of Markdown extended syntax;
        - Support AMD/CMD (Require.js & Sea.js) Module Loader, and Custom/define editor plugins;
        
        # Editor.md
        
        ![](https://pandao.github.io/editor.md/images/logos/editormd-logo-180x180.png)
        
        ![](https://img.shields.io/github/stars/pandao/editor.md.svg) ![](https://img.shields.io/github/forks/pandao/editor.md.svg) ![](https://img.shields.io/github/tag/pandao/editor.md.svg) ![](https://img.shields.io/github/release/pandao/editor.md.svg) ![](https://img.shields.io/github/issues/pandao/editor.md.svg) ![](https://img.shields.io/bower/v/editor.md.svg)
        
        
        **Table of Contents**
        
        [TOCM]
        
        [TOC]
        
        #H1 header
        ##H2 header
        ###H3 header
        ####H4 header
        #####H5 header
        ######H6 header
        #Heading 1 link [Heading link](https://github.com/pandao/editor.md "Heading link")
        ##Heading 2 link [Heading link](https://github.com/pandao/editor.md "Heading link")
        ###Heading 3 link [Heading link](https://github.com/pandao/editor.md "Heading link")
        ####Heading 4 link [Heading link](https://github.com/pandao/editor.md "Heading link") Heading link [Heading link](https://github.com/pandao/editor.md "Heading link")
        #####Heading 5 link [Heading link](https://github.com/pandao/editor.md "Heading link")
        ######Heading 6 link [Heading link](https://github.com/pandao/editor.md "Heading link")
        
        ##Headers (Underline)
        
        H1 Header (Underline)
        =============
        
        H2 Header (Underline)
        -------------
        
        ###Characters
                        
        ----
        
        ~~Strikethrough~~ <s>Strikethrough (when enable html tag decode.)</s>
        *Italic*      _Italic_
        **Emphasis**  __Emphasis__
        ***Emphasis Italic*** ___Emphasis Italic___
        
        Superscript: X<sub>2</sub>，Subscript: O<sup>2</sup>
        
        **Abbreviation(link HTML abbr tag)**
        
        The <abbr title="Hyper Text Markup Language">HTML</abbr> specification is maintained by the <abbr title="World Wide Web Consortium">W3C</abbr>.
        
        ###Blockquotes
        
        > Blockquotes
        
        Paragraphs and Line Breaks
                            
        > "Blockquotes Blockquotes", [Link](http://localhost/)。
        
        ###Links
        
        [Links](http://localhost/)
        
        [Links with title](http://localhost/ "link title")
        
        `<link>` : <https://github.com>
        
        [Reference link][id/name] 
        
        [id/name]: http://link-url/
        
        GFM a-tail link @pandao
        
        ###Code Blocks (multi-language) & highlighting
        
        ####Inline code
        
        `$ npm install marked`
        
        ####Code Blocks (Indented style)
        
        Indented 4 spaces, like `<pre>` (Preformatted Text).
        
            <?php
                echo "Hello world!";
            ?>
            
        Code Blocks (Preformatted text):
        
            | First Header  | Second Header |
            | ------------- | ------------- |
            | Content Cell  | Content Cell  |
            | Content Cell  | Content Cell  |
        
        ####Javascript　
        
        ```javascript
        function test(){
            console.log("Hello world!");
        }
         
        (function(){
            var box = function(){
                return box.fn.init();
            };
        
            box.prototype = box.fn = {
                init : function(){
                    console.log('box.init()');
        
                    return this;
                },
        
                add : function(str){
                    alert("add", str);
        
                    return this;
                },
        
                remove : function(str){
                    alert("remove", str);
        
                    return this;
                }
            };
            
            box.fn.init.prototype = box.fn;
            
            window.box =box;
        })();
        
        var testBox = box();
        testBox.add("jQuery").remove("jQuery");
        ```
        
        ####HTML code
        
        ```html
        <!DOCTYPE html>
        <html>
            <head>
                <mate charest="utf-8" />
                <title>Hello world!</title>
            </head>
            <body>
                <h1>Hello world!</h1>
            </body>
        </html>
        ```
        
        ###Images
        
        Image:
        
        ![](https://pandao.github.io/editor.md/examples/images/4.jpg)
        
        > Follow your heart.
        
        ![](https://pandao.github.io/editor.md/examples/images/8.jpg)
        
        > 图为：厦门白城沙滩 Xiamen
        
        图片加链接 (Image + Link)：
        
        [![](https://pandao.github.io/editor.md/examples/images/7.jpg)](https://pandao.github.io/editor.md/examples/images/7.jpg "李健首张专辑《似水流年》封面")
        
        > 图为：李健首张专辑《似水流年》封面
                        
        ----
        
        ###Lists
        
        ####Unordered list (-)
        
        - Item A
        - Item B
        - Item C
             
        ####Unordered list (*)
        
        * Item A
        * Item B
        * Item C
        
        ####Unordered list (plus sign and nested)
                        
        + Item A
        + Item B
            + Item B 1
            + Item B 2
            + Item B 3
        + Item C
            * Item C 1
            * Item C 2
            * Item C 3
        
        ####Ordered list
                        
        1. Item A
        2. Item B
        3. Item C
                        
        ----
                            
        ###Tables
                            
        First Header  | Second Header
        ------------- | -------------
        Content Cell  | Content Cell
        Content Cell  | Content Cell 
        
        | First Header  | Second Header |
        | ------------- | ------------- |
        | Content Cell  | Content Cell  |
        | Content Cell  | Content Cell  |
        
        | Function name | Description                    |
        | ------------- | ------------------------------ |
        | `help()`      | Display the help window.       |
        | `destroy()`   | **Destroy your computer!**     |
        
        | Item      | Value |
        | --------- | -----:|
        | Computer  | $1600 |
        | Phone     |   $12 |
        | Pipe      |    $1 |
        
        | Left-Aligned  | Center Aligned  | Right Aligned |
        | :------------ |:---------------:| -----:|
        | col 3 is      | some wordy text | $1600 |
        | col 2 is      | centered        |   $12 |
        | zebra stripes | are neat        |    $1 |
                        
        ----
        
        ####HTML entities
        
        &copy; &  &uml; &trade; &iexcl; &pound;
        &amp; &lt; &gt; &yen; &euro; &reg; &plusmn; &para; &sect; &brvbar; &macr; &laquo; &middot; 
        
        X&sup2; Y&sup3; &frac34; &frac14;  &times;  &divide;   &raquo;
        
        18&ordm;C  &quot;  &apos;
        
        ##Escaping for Special Characters
        
        \*literal asterisks\*
        
        ##Markdown extras
        
        ###GFM task list
        
        - [x] GFM task list 1
        - [x] GFM task list 2
        - [ ] GFM task list 3
            - [ ] GFM task list 3-1
            - [ ] GFM task list 3-2
            - [ ] GFM task list 3-3
        - [ ] GFM task list 4
            - [ ] GFM task list 4-1
            - [ ] GFM task list 4-2
        
        ###Emoji mixed :smiley:
        
        > Blockquotes :star:
        
        ####GFM task lists & Emoji & fontAwesome icon emoji & editormd logo emoji :editormd-logo-5x:
        
        - [x] :smiley: @mentions, :smiley: #refs, [links](), **formatting**, and <del>tags</del> supported :editormd-logo:;
        - [x] list syntax required (any unordered or ordered list supported) :editormd-logo-3x:;
        - [x] [ ] :smiley: this is a complete item :smiley:;
        - [ ] []this is an incomplete item [test link](#) :fa-star: @pandao; 
        - [ ] [ ]this is an incomplete item :fa-star: :fa-gear:;
            - [ ] :smiley: this is an incomplete item [test link](#) :fa-star: :fa-gear:;
            - [ ] :smiley: this is  :fa-star: :fa-gear: an incomplete item [test link](#);
                    
        ###Sankey
        ```mermaid
            ---
            config:
              sankey:
                showValues: false
            ---
            sankey-beta
            
            Agricultural 'waste',Bio-conversion,124.729
            Bio-conversion,Liquid,0.597
            Bio-conversion,Losses,26.862
            Bio-conversion,Solid,280.322
            Bio-conversion,Gas,81.144
            Biofuel imports,Liquid,35
            Biomass imports,Solid,35
            Coal imports,Coal,11.606
            Coal reserves,Coal,63.965
            Coal,Solid,75.571
            District heating,Industry,10.639
            District heating,Heating and cooling - commercial,22.505
            District heating,Heating and cooling - homes,46.184
            Electricity grid,Over generation / exports,104.453
            Electricity grid,Heating and cooling - homes,113.726
            Electricity grid,H2 conversion,27.14
            Electricity grid,Industry,342.165
            Electricity grid,Road transport,37.797
            Electricity grid,Agriculture,4.412
            Electricity grid,Heating and cooling - commercial,40.858
            Electricity grid,Losses,56.691
            Electricity grid,Rail transport,7.863
            Electricity grid,Lighting & appliances - commercial,90.008
            Electricity grid,Lighting & appliances - homes,93.494
            Gas imports,Ngas,40.719
            Gas reserves,Ngas,82.233
            Gas,Heating and cooling - commercial,0.129
            Gas,Losses,1.401
            Gas,Thermal generation,151.891
            Gas,Agriculture,2.096
            Gas,Industry,48.58
            Geothermal,Electricity grid,7.013
            H2 conversion,H2,20.897
            H2 conversion,Losses,6.242
            H2,Road transport,20.897
            Hydro,Electricity grid,6.995
            Liquid,Industry,121.066
            Liquid,International shipping,128.69
            Liquid,Road transport,135.835
            Liquid,Domestic aviation,14.458
            Liquid,International aviation,206.267
            Liquid,Agriculture,3.64
            Liquid,National navigation,33.218
            Liquid,Rail transport,4.413
            Marine algae,Bio-conversion,4.375
            Ngas,Gas,122.952
            Nuclear,Thermal generation,839.978
            Oil imports,Oil,504.287
            Oil reserves,Oil,107.703
            Oil,Liquid,611.99
            Other waste,Solid,56.587
            Other waste,Bio-conversion,77.81
            Pumped heat,Heating and cooling - homes,193.026
            Pumped heat,Heating and cooling - commercial,70.672
            Solar PV,Electricity grid,59.901
            Solar Thermal,Heating and cooling - homes,19.263
            Solar,Solar Thermal,19.263
            Solar,Solar PV,59.901
            Solid,Agriculture,0.882
            Solid,Thermal generation,400.12
            Solid,Industry,46.477
            Thermal generation,Electricity grid,525.531
            Thermal generation,Losses,787.129
            Thermal generation,District heating,79.329
            Tidal,Electricity grid,9.452
            UK land based bioenergy,Bio-conversion,182.01
            Wave,Electricity grid,19.013
            Wind,Electricity grid,289.366
        ```
                        
        
        ###Sequence Diagram
                            
        ```mermaid
            sequenceDiagram
            Andrew->China: Says Hello 
            Note right of China: China thinks\nabout it 
            China-->Andrew: How are you? 
            Andrew->>China: I am good thanks!
        ```
        
        ###End
    
servers:
    - url: "http://localhost:80"
      description: "Development server"
    - url: "http://localhost:8888"
      description: "Another server..."

paths:
    /users:
        get:
            summary: "Get all users"
            responses:
                200:
                    description: |
                    "Successful response"
                    content:
                        application/json:
                            schema:
                                type: "array"
                                items:
                                    $ref: "#/components/schemas/User"
        post:
            summary: "Create a new user"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
            responses:
                201:
                    description: "User created successfully"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
components:
    schemas:
        User:
            type: "object"
            properties:
                id:
                    type: "integer"
                name:
                    type: "string"
                email:
                    type: "string"
                age:
                    type: "integer"
